### PR TITLE
Migrate to yarn

### LINKED ISSUE #2: switch from `npm` to `yarn`
Low priority, but do so to match the rest of `mydsa`

### PR DESCRIPTION
**Pull request by nedredmond**
Migrated to Yarn and utilized the Workspace to clean up almost 2/3 of the scripts.

The scripts were getting difficult to maintain, and this strategy makes them much easier to grok. Plus, it seems like `yarn` is the package manager default for NTC.

Also beefs up the `version` script to create a new branch, tag it (after all versions have been bumped), and create a PR. Using this requires installation and configuration of the [GitHub CLI](https://cli.github.com/).

Resolves #2

### CODE REVIEW

**Comment by nedredmond** [comment]
Just realized I left out `"preversion"`, plus I'd like to generate a PR with `"postversion"`

**Comment by nedredmond** [comment]
Great-- everything is working as expected. Please review!

**Review by ysulyma — APPROVED** [review]
lgtm. A couple questions:
- it doesn't look like yarn is in our devDependencies, is this relying on a global yarn?
- this is for yarn v1?

**Comment by nedredmond** [comment]
@ysulyma Yes to both! I can add yarn as a dev dependency, but I don't think I've seen that before. It is for `yarn classic`-- is that a problem? I don't have any experience with `yarn 2` and it looks like I needed to download all kinds of plugins to make simple things work.

I can upgrade in the future if you think `yarn 2` would be better for the project. Classic seems to have everything I need and is easy to install and use.

**Comment by ysulyma** [comment]
@nedredmond just clarifying on the version, and I was mis-remembering about keeping package managers in package.json

**Pull request merged**
