### PR TITLE
Install Figma plugin for Storybook

### PR DESCRIPTION
**Pull request by ysulyma**
Install the [Storybook Figma addon](https://storybook.js.org/addons/storybook-addon-designs) which allows to link to Figma in stories

### CODE REVIEW

**Comment by nedredmond** [comment]
Can you get the Figma integration up and running on this branch?

**Comment by ysulyma** [comment]
@nedredmond this is all there is to do! We need story files to actually use it.

**Review by nedredmond — APPROVED** [review]

**Comment by nedredmond** [comment]
Would you remind removing `package-lock.json` from the PR?

**Comment by ysulyma** [comment]
removed!

**Review by nedredmond — APPROVED** [review]

**Pull request merged**
